apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 9076
    targetPort: {{ .Values.app.port }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.app.name }}
